-- ROSCA 平安商會系統預設使用者帳號建立腳本
-- 建立預設測試帳號: 0938766349 / 123456

USE rosca2;

-- 建立預設測試使用者
-- 密碼 '123456' 的 BCrypt hash (cost=12)
INSERT INTO `member_master` (
    `mm_id`,
    `mm_account`,
    `mm_hash_pwd`,
    `mm_2nd_hash_pwd`,
    `mm_name`,
    `mm_introduce_user`,
    `mm_introduce_code`,
    `mm_invite_user`,
    `mm_invite_code`,
    `mm_gender`,
    `mm_country_code`,
    `mm_personal_id`,
    `mm_phone_number`,
    `mm_mw_address`,
    `mm_email`,
    `mm_bank_code`,
    `mm_bank_account`,
    `mm_bank_account_name`,
    `mm_branch`,
    `mm_beneficiary_name`,
    `mm_beneficiary_phone`,
    `mm_beneficiary_relationship`,
    `mm_level`,
    `mm_role_type`,
    `mm_status`,
    `mm_kyc_id`,
    `mm_kyc`,
    `mm_create_member`,
    `mm_create_datetime`,
    `mm_update_member`,
    `mm_update_datetime`
) VALUES (
    1,
    '0938766349',
    '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBdXwtGtrKm9K2',
    '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBdXwtGtrKm9K2',
    '測試使用者',
    NULL,
    0,
    NULL,
    0,
    '1',
    '+886',
    'A123456789',
    '0938766349',
    '台北市信義區信義路五段7號',
    'test@example.com',
    '004',
    '1234567890123456',
    '測試使用者',
    '總行',
    '測試受益人',
    '0938766349',
    '本人',
    '1',
    '1',
    'Y',
    1,
    'Y',
    1,
    NOW(),
    1,
    NOW()
);

-- 建立對應的會員錢包
INSERT INTO `member_wallet` (
    `mw_id`,
    `mw_mm_id`,
    `mw_currency`,
    `mw_address`,
    `mw_subscripts_count`,
    `mw_stored`,
    `mw_reward`,
    `mw_peace`,
    `mw_mall`,
    `mw_registration`,
    `mw_death`,
    `mw_accumulation`,
    `mw_punish`,
    `mw_level`,
    `mw_create_member`,
    `mw_create_datetime`,
    `mw_update_member`,
    `mw_update_datetime`
) VALUES (
    1,
    1,
    'TWD',
    '台北市信義區信義路五段7號',
    0,
    10000.00000,  -- 給予初始存款點數 10000
    0.00000,
    0.00000,
    0.00000,
    1000.00000,   -- 給予註冊點數 1000
    0.00000,
    0.00000,
    0.00000,
    '1',
    1,
    NOW(),
    1,
    NOW()
);

-- 建立預設 KYC 認證記錄
INSERT INTO `apply_kyc_certification` (
    `akc_id`,
    `akc_mm_id`,
    `akc_name`,
    `akc_front`,
    `akc_back`,
    `akc_gender`,
    `akc_personal_id`,
    `akc_mw_address`,
    `akc_email`,
    `akc_bank_code`,
    `akc_bank_account`,
    `akc_bank_account_name`,
    `akc_branch`,
    `akc_beneficiary_name`,
    `akc_beneficiary_phone`,
    `akc_beneficiary_relationship`,
    `akc_status`,
    `akc_create_member`,
    `akc_create_datetime`,
    `akc_update_member`,
    `akc_update_datetime`
) VALUES (
    1,
    1,
    '測試使用者',
    'default_id_front.jpg',
    'default_id_back.jpg',
    '1',
    'A123456789',
    '台北市信義區信義路五段7號',
    'test@example.com',
    '004',
    '1234567890123456',
    '測試使用者',
    '總行',
    '測試受益人',
    '0938766349',
    '本人',
    '20',  -- 審核通過
    1,
    NOW(),
    1,
    NOW()
);

-- 建立管理員帳號
INSERT INTO `member_master` (
    `mm_id`,
    `mm_account`,
    `mm_hash_pwd`,
    `mm_2nd_hash_pwd`,
    `mm_name`,
    `mm_introduce_user`,
    `mm_introduce_code`,
    `mm_invite_user`,
    `mm_invite_code`,
    `mm_gender`,
    `mm_country_code`,
    `mm_personal_id`,
    `mm_phone_number`,
    `mm_mw_address`,
    `mm_email`,
    `mm_bank_code`,
    `mm_bank_account`,
    `mm_bank_account_name`,
    `mm_branch`,
    `mm_beneficiary_name`,
    `mm_beneficiary_phone`,
    `mm_beneficiary_relationship`,
    `mm_level`,
    `mm_role_type`,
    `mm_status`,
    `mm_kyc_id`,
    `mm_kyc`,
    `mm_create_member`,
    `mm_create_datetime`,
    `mm_update_member`,
    `mm_update_datetime`
) VALUES (
    2,
    'admin',
    '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBdXwtGtrKm9K2',
    '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBdXwtGtrKm9K2',
    '系統管理員',
    NULL,
    0,
    NULL,
    0,
    '1',
    '+886',
    'B987654321',
    'admin',
    '台北市信義區信義路五段7號',
    'admin@example.com',
    '004',
    '9876543210987654',
    '系統管理員',
    '總行',
    '系統管理員',
    'admin',
    '本人',
    '9',
    '2',  -- 管理員角色
    'Y',
    2,
    'Y',
    1,
    NOW(),
    1,
    NOW()
);

-- 建立管理員錢包
INSERT INTO `member_wallet` (
    `mw_id`,
    `mw_mm_id`,
    `mw_currency`,
    `mw_address`,
    `mw_subscripts_count`,
    `mw_stored`,
    `mw_reward`,
    `mw_peace`,
    `mw_mall`,
    `mw_registration`,
    `mw_death`,
    `mw_accumulation`,
    `mw_punish`,
    `mw_level`,
    `mw_create_member`,
    `mw_create_datetime`,
    `mw_update_member`,
    `mw_update_datetime`
) VALUES (
    2,
    2,
    'TWD',
    '台北市信義區信義路五段7號',
    0,
    999999.00000,  -- 管理員大額點數
    0.00000,
    0.00000,
    0.00000,
    0.00000,
    0.00000,
    0.00000,
    0.00000,
    '9',
    1,
    NOW(),
    1,
    NOW()
);

-- 建立管理員 KYC 認證記錄
INSERT INTO `apply_kyc_certification` (
    `akc_id`,
    `akc_mm_id`,
    `akc_name`,
    `akc_front`,
    `akc_back`,
    `akc_gender`,
    `akc_personal_id`,
    `akc_mw_address`,
    `akc_email`,
    `akc_bank_code`,
    `akc_bank_account`,
    `akc_bank_account_name`,
    `akc_branch`,
    `akc_beneficiary_name`,
    `akc_beneficiary_phone`,
    `akc_beneficiary_relationship`,
    `akc_status`,
    `akc_create_member`,
    `akc_create_datetime`,
    `akc_update_member`,
    `akc_update_datetime`
) VALUES (
    2,
    2,
    '系統管理員',
    'admin_id_front.jpg',
    'admin_id_back.jpg',
    '1',
    'B987654321',
    '台北市信義區信義路五段7號',
    'admin@example.com',
    '004',
    '9876543210987654',
    '系統管理員',
    '總行',
    '系統管理員',
    'admin',
    '本人',
    '20',  -- 審核通過
    1,
    NOW(),
    1,
    NOW()
);