# Docker Compose 生產環境配置
# 使用方式: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  # 生產環境 MariaDB 配置
  mariadb:
    # 生產環境不暴露資料庫端口
    ports: []
    # 生產環境資源限制
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # 生產環境日誌配置
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # 生產環境優化參數
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --init-connect='SET NAMES utf8mb4'
      --innodb-flush-log-at-trx-commit=1
      --sync-binlog=1
      --innodb-use-native-aio=1
      --innodb-buffer-pool-size=512M

  # 生產環境後端配置
  backend:
    # 生產環境不暴露後端端口
    ports: []
    # 生產環境資源限制
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
    # 生產環境日誌配置
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # 生產環境變數
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000
      Logging__LogLevel__Default: Warning
      Logging__LogLevel__Microsoft: Error

  # 生產環境前台配置
  frontend:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # 生產環境後台配置
  admin:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"