# MariaDB 服務配置 (Zeabur 部署用)
# 此檔案定義了 MariaDB 服務的完整配置

apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: rosca-mariadb
    tier: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: rosca-mariadb
    tier: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: rosca-mariadb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosca-mariadb
      tier: database
  template:
    metadata:
      labels:
        app: rosca-mariadb
        tier: database
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.3.2
        ports:
        - containerPort: 3306
          name: mysql
        env:
        # 基本資料庫設定
        - name: MYSQL_DATABASE
          value: "rosca_db"
        - name: MYSQL_USER
          value: "rosca_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mysql-root-password
        
        # 字符集設定
        - name: MYSQL_CHARACTER_SET_SERVER
          value: "utf8mb4"
        - name: MYSQL_COLLATION_SERVER
          value: "utf8mb4_general_ci"
        
        # 時區設定
        - name: TZ
          value: "Asia/Taipei"
        
        # 安全設定
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MYSQL_REMOVE_ANONYMOUS_USERS
          value: "yes"
        - name: MYSQL_REMOVE_TEST_DATABASE
          value: "yes"
        
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -u
            - ${MYSQL_USER}
            - -p${MYSQL_PASSWORD}
            - -e
            - "SELECT 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
      - name: mysql-config
        configMap:
          name: mysql-config
      - name: mysql-initdb
        configMap:
          name: mysql-initdb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  labels:
    app: rosca-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  labels:
    app: rosca-mariadb
type: Opaque
data:
  # 注意：這些是 base64 編碼的值，實際部署時需要替換
  # mysql-password: 你的資料庫密碼的 base64 編碼
  # mysql-root-password: 你的 root 密碼的 base64 編碼
  mysql-password: Um9zY2FTZWN1cmUyMDI0IUAj  # RoscaSecure2024!@#
  mysql-root-password: Um9vdFNlY3VyZTIwMjQhQCMk  # RootSecure2024!@#$

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: rosca-mariadb
data:
  my.cnf: |
    # MariaDB 11.3.2 配置文件 (Zeabur 優化版本)
    [mysqld]
    default-storage-engine = InnoDB
    sql_mode = STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER
    
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
    init-connect = 'SET NAMES utf8mb4'
    
    max_connections = 100
    max_connect_errors = 1000
    wait_timeout = 28800
    interactive_timeout = 28800
    connect_timeout = 10
    
    innodb_buffer_pool_size = 128M
    innodb_log_file_size = 32M
    innodb_log_buffer_size = 8M
    innodb_flush_log_at_trx_commit = 2
    
    query_cache_type = 1
    query_cache_size = 16M
    query_cache_limit = 1M
    
    tmp_table_size = 32M
    max_heap_table_size = 32M
    
    slow_query_log = 1
    slow_query_log_file = /var/log/mysql/slow.log
    long_query_time = 2
    
    log_bin = /var/log/mysql/mysql-bin.log
    binlog_format = ROW
    expire_logs_days = 3
    
    local_infile = 0
    skip_name_resolve = 1
    bind_address = 0.0.0.0
    port = 3306
    default_time_zone = '+08:00'
    
    [mysql]
    default-character-set = utf8mb4
    
    [client]
    default-character-set = utf8mb4
    port = 3306

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  labels:
    app: rosca-mariadb
data:
  01-schema.sql: |
    # 這裡會包含資料庫結構初始化腳本的內容
    # 實際部署時需要將 database/zeabur/docker-entrypoint-initdb.d/01-schema.sql 的內容複製到這裡
  
  02-default-data.sql: |
    # 這裡會包含預設資料載入腳本的內容
    # 實際部署時需要將 database/zeabur/docker-entrypoint-initdb.d/02-default-data.sql 的內容複製到這裡
  
  03-default-user.sql: |
    # 這裡會包含預設使用者建立腳本的內容
    # 實際部署時需要將 database/zeabur/docker-entrypoint-initdb.d/03-default-user.sql 的內容複製到這裡